import './globals.css'

import type { Metadata } from 'next'

import { Footer } from '@/_components/footer'
import { Header } from '@/_components/header'
import { fontSans } from '@/_lib/fonts'

export const metadata: Metadata = {
  title: 'That Movie',
  description: 'Generated by create next app',
}

type Props = Readonly<{ children: React.ReactNode }>

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} dark`}>
        <div className="container flex h-full flex-col overflow-x-hidden">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
